CREATE TABLE [dbo].[User]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[Name] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[UserName] NVARCHAR(100) NOT NULL,
	[Password] NVARCHAR(20) NOT NULL,
	[Email] NVARCHAR(50) NOT NULL,
	[PhoneNumber] NVARCHAR(20) NOT NULL,
	[Active] BIT DEFAULT 1 NOT NULL,
	[CreatedDate] DATETIME DEFAULT GETDATE() NOT NULL	
)
